# Generated by Django 5.2.7 on 2026-01-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer_percentage',
        ),
    ]
