# Generated by Django 6.0 on 2026-02-03 07:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_offer_percentage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_coupon_code_case_insensitive'),
        ),
    ]
