# Generated by Django 6.0 on 2026-02-03 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_coupon_unique_coupon_code_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='jerseyproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
