# Generated by Django 5.2.7 on 2026-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_jerseyproduct_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jerseyproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
